dj/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import logout
from account.views import register,register2,login,update,confirm,verify,reset,forgot,testEmail,deleteUser,approveUser,declineUser

urlpatterns = [
	
	url(r'^register/restaurant', register2,name='register2'),
	url(r'^testemail/', testEmail,name='register'),
	url(r'^register/', register,name='register'),
	url(r'^delete/user/(?P<id>[0-9]+)', deleteUser,name='deleteUser'),
	url(r'^approve/appr/(?P<id>[0-9]+)', approveUser,name='approveUser'),
	url(r'^approve/decline/(?P<id>[0-9]+)', declineUser,name='declineUser'),
	url(r'^login/$', login, name='login'),
	url(r'^update/$', update, name='update'),
	url(r'^reset/(?P<token>[-\w]+)$', reset, name='reset'),
	url(r'^forgot/$', forgot, name='forgot'),
	url(r'^confirm/$', confirm, name='confirm'),
	url(r'^verify/(?P<token>[-\w]+)$', verify, name='verify'),
	url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
	url(r'^dashboard/', include('dashboard.urls')),
	url('^api/v1/', include('social_django.urls', namespace='social')),
	url(r'^articles/', include('blog.urls')),
	url(r'^restaurants/', include('restaurant.urls')),
	url(r'^order/', include('cart.urls')),
	url(r'^admin/', admin.site.urls),
	url(r'^', include('pages.urls')),
]

account/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import Group, PermissionsMixin
from rest_framework import serializers
from django import forms
from django.core.mail import send_mail
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.base_user import BaseUserManager
from dj import settings

class UserManager(BaseUserManager):
	use_in_migrations = True
	def _create_user(self,username, email, password, **extra_fields):
		if not email:
			raise ValueError('The given email must be set')
		email = self.normalize_email(email)
		user = self.model(email=email, **extra_fields)
		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_user(self,username, email, password=None, **extra_fields):
		extra_fields.setdefault('is_superuser', False)
		return self._create_user(email,username, password, **extra_fields)

	def create_superuser(self, email, password, **extra_fields):
		extra_fields.setdefault('is_superuser', True)
		if extra_fields.get('is_superuser') is not True:
			raise ValueError('Superuser must have is_superuser=True.')
		return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
	email = models.EmailField(unique=True)
	first_name = models.CharField(max_length=40, blank=True,null=True)
	last_name = models.CharField(max_length=40, blank=True,null=True)
	token = models.CharField(max_length=30, blank=True,null=True)
	forgot = models.CharField(max_length=30, blank=True,null=True)
	admin = models.BooleanField(default=False)
	editor = models.BooleanField(default=False)
	active = models.BooleanField(_('active'), default=True)
	date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
	avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
	addres = models.CharField(verbose_name='Address',max_length=240, blank=True,null=True)
	city = models.CharField(verbose_name='City',max_length=240, blank=True,null=True)
	state = models.CharField(verbose_name='State',max_length=240, blank=True,null=True)
	zip = models.CharField(verbose_name='Zip',max_length=240, blank=True,null=True)
	mobile = models.IntegerField(verbose_name='Phone no',blank=True,null=True)
	bio = models.TextField(max_length=500, blank=True)
	birth_date = models.DateField(null=True, blank=True)
	def __unicode__(self):
		return self.email
	objects = UserManager()

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	class Meta:
		verbose_name = _('user')
		verbose_name_plural = _('users')

	def email_user(self, subject, message, from_email=None, **kwargs):
		send_mail(subject, message, from_email, [self.email], **kwargs)

class Address(models.Model):
	title = models.CharField(max_length=20)
	house = models.CharField(verbose_name='Address',max_length=200)
	suite = models.CharField(verbose_name='Apt/Suite',max_length=80,null=True, blank=True)
	city = models.CharField(max_length=80)
	state = models.CharField(max_length=40)
	zip_code = models.CharField(max_length=20)
	phone = models.CharField(max_length=20)
	cross_street = models.CharField(max_length=80,null=True, blank=True)
	instructions = models.CharField(max_length=400,null=True, blank=True)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class UserSerializer(serializers.HyperlinkedModelSerializer):
	class Meta:
		model = User
		fields = ('url', 'username', 'email', 'groups')

class GroupSerializer(serializers.HyperlinkedModelSerializer):
	class Meta:
		model = Group
		fields = ('url', 'name')


class AddressForm(forms.ModelForm):
	class Meta:
		model = Address
		fields = ['title','house','suite','city','state','zip_code','phone','cross_street','instructions']

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django import forms
from dj import settings

class Article(models.Model):
	created = models.DateField(auto_now_add=True, blank=True)
	title = models.CharField(max_length=200)
	content = models.TextField()
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)



class ArticleForm(forms.ModelForm):
	class Meta:
		model = Article
		fields = ['title','content']

templates/order/checkout.html
{% extends 'base.html' %}

{% block content %}
<div class="pickup-widget">
	<div class="row">
		<div class="header clearfix">
			<h2 class="pull-left">Order</h2>
			<a href="/restaurants/{{order.restaurant.id}}" class="back-btn pull-right">Back</a>
		</div>
		<div class="col col-sm-12 no-padding border-cont">
		  {% if order %}
			<table class="table">
				{% for item in items %}			
				<tr>
					<td width="20%"><img src="/static/ImagesCiiboo/catd-dummy-img.png" width="40" height="40"></td>
					<td width="60%">{{item.cuisine.title}}</td>
					<td width="20%">{{item.quantity}} <i class="fa fa-times"></i> {{item.cuisine.price}} <b>=</b> {{item.amount}}</td>				
				</tr>
				{% endfor %}
				<tr class="border">
					<td>&nbsp;</td>
					<td><b>Total:</b></td>
					<td><b>{{total}}</b></td>
				</tr>	
				{% else %}
				<h4>Add From Menu to Order</h4>
				{% endif %}
			</table>
		</div>
		{% if order.address %}
		<div class="col col-sm-12 section-part border-cont">
			<div class="header clearfix">
				<h2 class="pull-left">Address</h2>
				<button type="button" class="back-btn pull-right" data-toggle="modal" data-target="#pickup-address">Change</button>
			</div>
			<div class="col-md-4"><b>Address Title :&nbsp; </b>{{order.address.title}}</div>
			<div class="col-md-4"><b>House :&nbsp; </b>{{order.address.house}}</div>
			<div class="col-md-4"><b>City :&nbsp; </b>{{order.address.city}} - {{order.address.pin}}</div>
			<div class="col-md-4"><b>State :&nbsp; </b>{{order.address.state}}</div>
			<div class="col-md-4"><b>Phone :&nbsp; </b>{{order.address.phone}}</div>
			<div id="pickup-address" class="pop-up-common-widget modal fade" role="dialog">
		        <div class="modal-dialog">
		          <!-- Modal content-->
		          <div class="modal-content">
		          <button type="button" class="close" data-dismiss="modal">
		                     <img src="/static/ImagesCiiboo/close-icon.png">
		                 </button>                 
		              <div class="modal-body">
		                 <div class="auth Login">                 
		                    <div class="login-icon">
		                        <img src="/static/ImagesCiiboo/as-user-icon.png">
		                    </div>                
		                     <h2>Change Address</h2>
			                  <form action="/order/{{order.id}}/checkout/{{order.address.id}}/update" method="post">
								{% csrf_token %}
								{{ form.as_p }}
								<input type="submit" value="Update" class="btn btn-success" />
							</form>        			  
		               </div>               
		             </div>
		          </div>
		        </div>
		 	</div>
		</div>
		{% endif %}		
		<div class="col col-sm-12 section-part border-cont">		
			<div class="header clearfix">
				<h2 class="pull-left">Select Payment</h2>				
			</div>
			<div class="col-sm-12">
				<form action="/order/{{order.id}}/payment" method="POST">
					{% csrf_token %}
					<script
					src="https://checkout.stripe.com/checkout.js" class="stripe-button"
					data-key="{{stripekey}}"
					data-amount="{%widthratio total 1 100%}"
					data-email="{{user.email}}"
					data-name="Ciibbo"
					data-description="Widget"
					data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
					data-locale="auto"
					data-zip-code="true">
					</script>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/order/done.html
{% extends 'base.html' %}

{% block content %}
<div  style="border: 2px solid #222222;padding: 0px;margin: 0px;">
	<div style="background-color: #222222;">
		<h2 style="color: white"><strong>Great, Your order is Placed!</strong></h2>
	</div>

	<div class="row">
		<div class="col col-sm-4">
			<img src="/static/ImagesCiiboo/thankyou.png" width="auto" />
		</div>
		<div class="col col-sm-4" >
			{% if order %}
			<h4>Order #{{order.id}} from <i>{{order.restaurant.title}}</i></h4>
			<h4><strong>Total: {{total}}</strong></h4>
			<h4>Delivery Address:</h4>
			<h4>{{order.address.title}}</h4>
			<p>{{order.address.house}}</p>
			<p>{{order.address.street}}</p>
			<p>{{order.address.city}} - {{order.address.pin}}</p>
			<p>{{order.address.phone}}</p>

			{% else %}
			<h4>Add From Menu to Order</h4>
			{% endif %}

		</div>
		{% if order.address %}
		<div class="col col-sm-4">

		</div>
		{% endif %}

		<div class="col col-sm-4">
			<h3>Payment</h3>

		</div>

	</div>
</div>
{% endblock %}

templates/order/index.html
{% extends 'base.html' %}

{% block content %}
 
<div class="row restaurant-inner-popular-widget delivery-page-widget">	
	<div class="col col-sm-8 box-shadow">
		<img src="/static/ImagesCiiboo/orderback.jpg">
		<div class="clearfix mrg-20">
			<div class="col-md-9 col-xs-6">
				<div class="select-ad">Select Address</div>
			</div>
		  <div class="col-md-3 col-xs-6 no-padding">
         	<button type="button" class="add-new-address" data-toggle="modal" data-target="#delivery-add-address">Add new Address <img src="/static/ImagesCiiboo/add-new-btn.png">
         	 </button>
				<div id="delivery-add-address" class="pop-up-common-widget modal fade" role="dialog">
				        <div class="modal-dialog">
				          <!-- Modal content-->
				          <div class="modal-content">
				          <button type="button" class="close" data-dismiss="modal">
				                     <img src="/static/ImagesCiiboo/close-icon.png">
				                 </button>                 
				              <div class="modal-body">
				                 <div class="auth Login">                 
				                    <div class="login-icon">
				                        <img src="/static/ImagesCiiboo/as-user-icon.png">
				                    </div>                
				                     <h2>Add New Address</h2>
										<form action="/order/{{order.id}}/addAddress" method="post">
											{% csrf_token %}
											{% for users in users %}	
											<p><label for="id_title">Title:</label> 
											<input type="text" name="title" required="" id="id_title"  maxlength="20"></p>
											<p><label for="id_house">Address:</label> <input type="text" name="house" required="" value="{{users.addres}}" id="id_house" maxlength="200"></p>
											<p><label for="id_suite">Apt/Suite:</label> <input type="text" name="suite" id="id_suite" maxlength="80"></p>
											<p><label for="id_city">City:</label> <input type="text" name="city" required="" value="{{users.city}}" id="id_city" maxlength="80"></p>
											<p><label for="id_state">State:</label> <input type="text" name="state" required="" id="id_state" value="{{users.state}}" maxlength="40"></p>
											<p><label for="id_zip_code">Zip code:</label> <input type="text" name="zip_code" required="" value="{{users.zip}}" id="id_zip_code" maxlength="20"></p>
											<p><label for="id_phone">Phone:</label> <input type="text" name="phone" required="" id="id_phone" value="{{users.mobile}}" maxlength="20"></p>
											<p><label for="id_cross_street">Cross street:</label> <input type="text" name="cross_street" id="id_cross_street" maxlength="80"></p>
											<p><label for="id_instructions">Instructions:</label> <input type="text" name="instructions" id="id_instructions" maxlength="400"></p>
											
											 {% endfor %}
											<input type="submit" value="Add" class="btn btn-success" />
										</form>
				 				</div>               
				             </div>
				          </div>
				        </div>
					</div>
				</div>
		</div>		

		 {% for address in addresses %}
			{% ifequal address.id order.address.id %}
			<div class="col col-sm-12 widget-color clearfix">{% else %}
				<div class="col-sm-12 widget-color clearfix">
					{% endifequal %}
					<div class="col-md-12">					
						<b>Address title :&nbsp; </b>
						<a href="/order/{{order.id}}/selectAddress/{{address.id}}">{{address.title}}</a>					
					</div>
					<div class="col-md-4"><b>Address House&nbsp;:&nbsp;</b>{{address.house}}</div>
					
					<div class="col-md-4"><b>Address City&nbsp;:&nbsp;</b>{{address.city}}</div>
					<div class="col-md-4"><b>Address State&nbsp;:&nbsp;</b>{{address.state}}</div>
					<div class="col-md-4"><b>Address Pin&nbsp;:&nbsp;</b>{{address.zip_code}}</div>
					<div class="col-md-4"><b>Address Phone&nbsp;:&nbsp;</b>{{address.phone}}</div>
					
                {% if address.id != order.address.id %}
				<div class="col-md-12 no-padding">
					<button onclick="location.href='/order/{{order.id}}/address/{{address.id}}/delete'" class="btn-remove" type="button">Remove</button>
     			</div>
			     {% endif %}
			</div>
			{% endfor %}	

	</div>
	<div class="col col-sm-4">
		<div class="brd-cart-payment-widget">			
			<div class="clearfix cart-here">			
				<div class="pull-left">
					<div class="cart-icon">
						<img src="/static/ImagesCiiboo/cart-icon.png">Cart Here
					</div>
				</div>
				<div class="pull-right">
					<a href="/restaurants/{{order.restaurant.id}}" class="back-btn">Back</a>
				</div>
			</div>	 
			{% if order %}
			<table class="table payment-cart">
				{% for item in items %}			
					<tr>
						<td width="20%" class="text-cap"><img src="/static/ImagesCiiboo/catd-dummy-img.png" width="50" height="50"></td>						
						<td width="70%">
							<div class="text-cap">{{item.cuisine.title}}</div>
							<div class="price-cal">{{item.quantity}}<i class="fa fa-times"></i> {{item.cuisine.price}} <b>=</b> {{item.amount}}
							</div>
						</td>
						<td width="10%">
							<button onclick="location.href='/order/{{order.id}}/address/{{item.id}}/delete1'" class="cross-btn" type="button">
		     Remove</button> 
		     			 </td>
					</tr>			
				{% endfor %}
			</table>
			<table class="list-total">
				<tr>
					<td width="30%">Sub total</td>
					<td width="20%">&nbsp;</td>
					<td width="50%">{{total}}</td>					
				</tr>
			</table>
	        
			
			{% else %}
			<h4>Add From Menu to Order</h4>
			{% endif %}
	   			 {% if order.address %}
					<a href="/order/{{order.id}}/checkout" class="proceed-btn btn-success">Proceed</a>
			{% else %}
			<h4>Please select an Address</h4>
			{% endif %}
		</div>
	</div>
</div>

{% endblock %}